# Generated by Django 4.1 on 2022-09-09 19:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='campaign',
            name='image',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
