# Generated by Django 4.1 on 2022-09-10 13:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0002_campaign_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='campaign',
            old_name='Location',
            new_name='location',
        ),
    ]
