# Generated by Django 4.1 on 2022-09-10 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0006_remove_joinedcampaign_title_campaign_comments_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='campaign',
            name='comments',
        ),
        migrations.DeleteModel(
            name='JoinedCampaign',
        ),
    ]
