# Generated by Django 4.1 on 2022-09-10 14:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_alter_customuser_image'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('post', '0002_remove_comment_author_remove_post_comments'),
    ]

    operations = [
        migrations.AddField(
            model_name='comment',
            name='author',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='post',
            name='comments',
            field=models.ManyToManyField(related_name='comments', through='post.Comment', to=settings.AUTH_USER_MODEL),
        ),
    ]
