# Generated by Django 4.1 on 2022-09-12 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('post', '0003_comment_author_post_comments'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='comments',
        ),
    ]
