# Generated by Django 4.1 on 2022-09-10 13:37

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_remove_campaign_organizer'),
        ('accounts', '0004_alter_customuser_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='joined_campaigns',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campaigns', models.ManyToManyField(blank=True, null=True, to='campaign.campaign')),
                ('user', models.ManyToManyField(to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
