# Generated by Django 4.1 on 2022-09-10 13:44

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('campaign', '0004_remove_campaign_organizer'),
        ('accounts', '0006_remove_joined_campaigns_campaigns_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='joined_campaigns',
            name='campaigns',
        ),
        migrations.RemoveField(
            model_name='joined_campaigns',
            name='user',
        ),
        migrations.AddField(
            model_name='joined_campaigns',
            name='campaigns',
            field=models.ManyToManyField(blank=True, null=True, to='campaign.campaign'),
        ),
        migrations.AddField(
            model_name='joined_campaigns',
            name='user',
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
