# Generated by Django 4.1 on 2022-09-10 14:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_remove_joined_campaigns_campaigns_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='joined_campaigns',
        ),
    ]
